name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'  # include pre-releases like v1.2.3-beta.1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Detect pre-release
        id: prerelease
        run: |
          if [[ "${GITHUB_REF##*/}" == *"-"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        run: |
          if [[ "${{ steps.prerelease.outputs.is_prerelease }}" == "true" ]]; then
            npm publish --tag beta
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
